### ISSUE TITLE
Orthographic profile Gothic, Braune 2004

### ISSUE THREAD

**Issue by martino-vic** [orthograpy/orthograpy-profiles#1]
First of all thank you @LinguList for pointing me to this database in [this thread](https://github.com/martino-vic/streitberggothic/issues/2#issuecomment-1007913570), it would have saved me a lot of work if I had known about this earlier! But better late than never, I'm glad I learned about this. Since I however already reinvented the wheel in the specific case of Gothic, as described in Braune 2004, I'd have a comment or idea for improvement to make: 

On p.47 Braune writes about the graphemes <l, r, m, n> that "postkonsonantisch im Auslaut (stikl, akr, [smakka-]bagm, fraihri) oder postkonsonantisch vor -s (stikls, akrs, maipms, taikns)" they are  "sonantisch und silbebildend", so that would mean IPA <l̥ m̥ n̥ r̥> (I'm not acquainted enough with this transcription system here though, maybe those sepcial characters are disencouraged here?)

and on p.63 he writes: "\<b\> entspricht dem griech. ß, z.B. barbarus βάρβαρος, Iakobus Ι ά κ ω β ο ς , Akk. Iakob 'Ιακώβ. Die Aussprache des griech. β war die eines stimmhaften labialen Spiranten. Meist wird angenommen, daß got. b im Inlaut nach Vokalen die Geltung eines stimmhaften (bilabialen) Spiranten habe, dagegen im Anlaut und inlautend nach Konsonanten den stimmhaften Verschlußlaut bezeichne.", So generally the grapheme \<b\> would correspond to IPA <β>, except word finally and after consonants it would be \<b\>. The same idea applies to \<d\> and \<g\> as well.

I tried to caption this in [my recent contribution](https://github.com/dmort27/epitran/blob/master/epitran/data/post/got-Latn.txt) to the Python library "epitran" in the form of a post-processing file in the IPA-transcriber:
```
::consonant:: = n|z|ɣ|k|s|ɸ|c|m|v|b|w|d|r|l|t|β|ð|j|p|ŋ|θ|ɡ|x|h

% restore initial <b>, <d>, <ɡ> 
β -> b / # _
ð -> d / # _
ɣ -> ɡ / # _ 

% restore <b>, <d> as geminates
ββ -> bb / _
ðð -> dd / _

% restore <b>, <d>, <g> before consonants
β -> b / (::consonant::) _
ð -> d / (::consonant::) _
ɣ -> ɡ / (::consonant::) _ 

% mark syllabic <l>, <m>, <n>, <r> between consonants

l -> l̥ / (::consonant::) _ (::consonant::)
m -> m̥ / (::consonant::) _ (::consonant::)
n -> n̥ / (::consonant::) _ (::consonant::)
r -> r̥ / (::consonant::) _ (::consonant::)
``` 
I should maybe also add that [this](https://github.com/dmort27/epitran/blob/master/epitran/data/map/got-Latn.csv) was the file that I created for the transcription - it includes also graphemes with all kinds of special characters that showed up in the data. 

From what I've seen on https://digling.org/calc/profile/ this dimension of the transcription is not yet captured, so I was wondering: Would it be approporiate and would the framework allow for including it here as well? And if yes, how would the procedure look like, would it work via a simple pull request? Thanks in advance for reading this overly long post and thanks again for introducing me to this repository!

**Comment by LinguList** [comment]
To capture this dimension the respective cases would have to be spelled out, as we do not allow for rules in our profiles. So you'd have to buildt, e.g., the cartesian product of "β" with all consonants, and write it into one line each:

βk -> b k
βg -> b g

etc.

This can in fact be easily done with the [profiler](https://digling.org/calc/profiler/), more specifically: the rule generator for orthography profiles. The result is a longer profile, in which all individual interpretations of one rule are added to one line.

I think this would be nice, and I'd recommend to first implement it on your 4000+ Gothic words in the lexibank dataset.

**Comment by martino-vic** [comment]
Ah that's awesome! I'm going to work on this then and come up with a pull request soon! I assume the special characters (like <á, à etc.> that all map to the same IPA symbol <a>) I assume they should then best be shifted to the pre-processing with pylexibank ("form_spec") in order to reduce the size of the cartesian product, right?

**Comment by LinguList** [comment]
You can add them as a unicode symbol in the profiler ;)

**Comment by martino-vic** [comment]
I used the profiler to create [orthography.tsv](https://github.com/martino-vic/streitberggothic/blob/new/etc/orthography.tsv) but the [transcriptions](https://github.com/martino-vic/streitberggothic/blob/new/cldf/forms.csv) have a few mistakes that I don't see how I could circumnavigate within the current framework, e.g. abrs -> aβr s is wrong - the r needs to be syllabic. So for now I've added an extra column IPA with a [separate script](https://github.com/martino-vic/streitberggothic/blob/new/etc/addipa.py) that I included in `etc`, together with the transcription rules. The script uses the epitran library.

Created a new [pull request](https://github.com/orthograpy/orthograpy-profiles/pull/2), limitations described [here](https://github.com/martino-vic/streitberggothic/issues/3)
